---
- name: Create {{ rhpam_business_central_data }} directory
  file:
    path: "{{ rhpam_business_central_data }}"
    state: directory

# Business Central basic config
- name: Create setup-basic-props.cli
  template:
    src: setup-basic-props.cli.j2
    dest: "{{ rhpam_business_central_tmp_dest }}/setup-basic-props.cli"

- name: Run setup-basic-props.cli to add Business Central basic configurations
  command: "{{ rhpam_business_central_home }}/bin/jboss-cli.sh --file={{ rhpam_business_central_tmp_dest }}/setup-basic-props.cli"

# Custom maven config
- name: Create {{ kie_maven_settings_custom }}
  template:
    src: settings.xml.j2
    dest: "{{ kie_maven_settings_custom }}"

- name: Create bc-setup-maven-props.cli
  template:
    src: setup-maven-props.cli.j2
    dest: "{{ rhpam_business_central_tmp_dest }}/bc-setup-maven-props.cli"

- name: Run bc-setup-maven-props.cli to add custom maven configuration
  command: "{{ rhpam_business_central_home }}/bin/jboss-cli.sh --file={{ rhpam_business_central_tmp_dest }}/bc-setup-maven-props.cli"

# SSH keys necessary to git clone (import projects) and push via SSH.
- name: Generate SSH key pair {{ rhpam_business_central_ssh_key }}
  openssh_keypair:
    path: "{{ rhpam_business_central_ssh_key }}"
  register: openssh_keypair

- name: Upload SSH public key to github.com
  github_key:
    name: rhpam-business-central
    token: "{{ github_access_token }}"
    pubkey: "{{ openssh_keypair.public_key }}"
  delegate_to: localhost
  when: github_access_token is defined

# Add & configure Red Hat Single Sign-On OIDC Adapter
- name: Downloading Red Hat Single Sign-On Client Adapter for JBoss EAP 7 into {{rhpam_business_central_tmp_dest}} from Red Hat Customer Portal, please wait ...
  redhat_csp_download:
    url: "{{redhat_sso_oidc_eap_adapter_package_source}}"
    dest: "{{rhpam_business_central_tmp_dest}}/{{redhat_sso_oidc_eap_adapter_package_name}}"
    username: "{{rhn_username}}"
    password: "{{rhn_password}}"
  vars:
    ansible_python_interpreter: "{{ansible_python_interpreter_path}}"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Extract Red Hat Single Sign-On Client Adapter for JBoss EAP 7 into {{ rhpam_business_central_home }}
  unarchive:
    src: "{{ rhpam_business_central_tmp_dest }}/{{redhat_sso_oidc_eap_adapter_package_name}}"
    dest: "{{ rhpam_business_central_home }}"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Configure Red Hat Single Sign-On Client Adapter for JBoss EAP 7
  command: "{{ rhpam_business_central_home }}/bin/jboss-cli.sh -Dserver.config=standalone-full.xml --file={{ rhpam_business_central_home }}/bin/adapter-elytron-install-offline.cli"
  when: use_redhat_sso_oidc_eap_adapter is defined
  tags:
    - sso

- name: Create bc-setup-sso-props.cli
  template:
    src: setup-sso-props.cli.j2
    dest: "{{ rhpam_business_central_tmp_dest }}/bc-setup-sso-props.cli"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Run bc-setup-sso-props.cli to add Business Central rh-sso configuration
  command: "{{ rhpam_business_central_home }}/bin/jboss-cli.sh --file={{ rhpam_business_central_tmp_dest }}/bc-setup-sso-props.cli"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Create kie-git.json
  template:
    src: kie-git.json.j2
    dest: "{{ rhpam_business_central_tmp_dest }}/kie-git.json"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Copy kie-git.json to {{ rhpam_business_central_home }}
  command:
    cmd: "cp -rf {{ rhpam_business_central_tmp_dest }}/kie-git.json {{ rhpam_business_central_home }}"
    creates: "{{ rhpam_business_central_home }}/kie-git.json"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Create bc-setup-sso-client.cli
  template:
    src: setup-sso-client.cli.j2
    dest: "{{ rhpam_business_central_tmp_dest }}/bc-setup-sso-client.cli"
  when: use_redhat_sso_oidc_eap_adapter is defined

- name: Run bc-setup-sso-client.cli to add rh-sso client configuration
  command: "{{ rhpam_business_central_home }}/bin/jboss-cli.sh --file={{ rhpam_business_central_tmp_dest }}/bc-setup-sso-client.cli"
  when: use_redhat_sso_oidc_eap_adapter is defined
