---
- name: Create {{ rhpam_kie_server_tmp_dest }} installation directory
  file:
    path: "{{ rhpam_kie_server_tmp_dest }}"
    state: directory

- name: Downloading RHPAM Kie Server into {{rhpam_kie_server_tmp_dest}} from Red Hat Customer Portal, please wait ...
  redhat_csp_download:
    url: "{{rhpam_kie_server_package_source}}"
    dest: "{{rhpam_kie_server_tmp_dest}}/{{rhpam_kie_server_package_name}}"
    username: "{{rhn_username}}"
    password: "{{rhn_password}}"
  async: 7200
  poll: 0
  register: csp_kie_server_download
  vars:
    ansible_python_interpreter: "{{ansible_python_interpreter_path}}"

- name: Check On RHPAM Kie Server download completion ...
  async_status: jid={{ csp_kie_server_download.ansible_job_id }}
  register: job_result_csp_kie_server_download
  until: job_result_csp_kie_server_download.finished
  retries: 600
  delay: 10
