org_kie_example: "true"
org_jbpm_designer_perspective: "full"
designerdataobjects: "false"
org_kie_workbench_profile: "FORCE_FULL"
org_jbpm_server_ext_disabled: "false"
org_jbpm_ui_server_ext_disabled: "false"

rhpam_business_central_ssh_key: "{{ ansible_user_dir }}/.ssh/rhpam_rsa"
org_uberfire_nio_git_dir: "{{ rhpam_business_central_data }}"
org_uberfire_metadata_index_dir: "{{ rhpam_business_central_data }}"
org_uberfire_nio_git_ssh_cert_dir: "{{ rhpam_business_central_data }}"

# org_uberfire_nio_git_hooks: "{{ rhpam_business_central_data }}/git-hooks"
# appformer_git_hooks_bundle: "{{ rhpam_business_central_data }}/git-hook-messages.properties"

org_guvnor_m2repo_dir: "{{ rhpam_business_central_data }}/repositories/kie"
kie_maven_settings_custom: "{{ rhpam_business_central_data }}/settings.xml"
